version: '2'
services:
  reverseproxy:
    build: ./reverseproxy
    ports:
      - 8001:8001

  app:
    build: ./app
    volumes:
     - ./app:/usr/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://admin:pass@postgres/main
      DATABASE: main
      DATABASE_USER: admin
      DATABASE_PASSWORD: pass
      DATABASE_HOST: postgres
      NODE_ENV: development

  front:
    build: ./frontend/app
    volumes:
     - ./frontend/app:/usr/app
    ports:
      - "8080:8080"
  postgres:
    image: postgres:9.6.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: main
